controller:
  allowSnippetAnnotations: true
  config:
    use-proxy-protocol: "true"
    http-snippet: |
      proxy_cache_path /tmp/nginx-cache levels=1:2 keys_zone=static-cache:2m max_size=100m inactive=7d use_temp_path=off;
      proxy_cache_key $scheme$proxy_host$request_uri;
      proxy_cache_lock on;
      proxy_cache_use_stale updating;

  kind: DaemonSet
  service:
    externalTrafficPolicy: Local
    type: LoadBalancer
    annotations: 
      load-balancer.hetzner.cloud/name: "app-production-lb"
      load-balancer.hetzner.cloud/location: "hel1"
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
rbac:
  create: true