all:
  children:
    workers:
      hosts:
        worker1.dealercy.net:
          ansible_host: 65.21.3.204
          ansible_user: root
  hosts:
    master.dealercy.net:
      ansible_host: 95.217.157.166
      ansible_user: root
