- hosts: master.dealer.com.cy
  tasks:
    - name: Install nfs packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - nfs-kernel-server

    - name: Create a mountable directory if it does not exist
      file:
        path: /var/kubernetes
        state: directory
        owner: root
        group: root
        mode: '0775'

    - name: enable rpcbind nfslock nfs
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - rpcbind

    - name: Copy exports file.
      template:
        src: ../exports/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a

- hosts: workers
  tasks:
    - name: Install nfs packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - nfs-kernel-server

    - name: Create a mountable directory if it does not exist
      file:
        path: /var/kubernetes
        state: directory
        owner: root
        group: root
        mode: '0775'
    - name: Mount volumn
      shell: sudo mount {{ hostvars['master.dealer.com.cy'].ansible_host }}:/var/kubernetes /var/kubernetes
