name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manually trigger the workflow
    inputs:
      enviroment:
        description: 'Choose enviroment from terraform/<enviroment>'
        required: true
        default: 'staging'

jobs:
  Destroy-Infrastructure:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          if ! command -v terraform &> /dev/null; then
            curl -fsSL https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip -o terraform.zip
            unzip -o terraform.zip
            sudo mv terraform /usr/local/bin/
            rm terraform.zip
          fi

      - name: Verify installations
        run: terraform --version

      - name: Configure Terraform variables
        working-directory: ./terraform/${{ github.event.inputs.enviroment }}
        id: vars
        run: |-
          sed -i 's/MINIO_ACCESS_KEY/${{ secrets.MINIO_ACCESS_KEY }}/' config.tf
          sed -i 's/MINIO_SECRET_KEY/${{ secrets.MINIO_SECRET_KEY }}/' config.tf 
      
      - name: Terraform initialization
        working-directory: ./terraform/${{ github.event.inputs.enviroment }}
        run: terraform init

      - name: Terraform Plan Destroy
        working-directory: ./terraform/${{ github.event.inputs.enviroment }}
        run: |
          cat >> variables.tfvars <<EOF

          hcloud_token = "${{ secrets.HCLOUD_TOKEN }}"
          ssh_key = "${{ secrets.CHRIS_SSH_KEY }}"
          EOF
          terraform plan -destroy -var-file=variables.tfvars
      
      - name: Destroying Enviroment!
        working-directory: ./terraform/${{ github.event.inputs.enviroment }}
        run: terraform apply -destroy -var-file=variables.tfvars -auto-approve